//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductCRUD.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [Required]

        [Display(Name = "Please enter the product name")]
        public string Name { get; set; }

        [Required]
        [Range(1,10000)]
        [Display(Name = "Enter the product price")]
        public string Price { get; set; }

        [Required]
        [MaxLength(100)]
        [MinLength(1)]
        [Display(Name = "Enter the product quantity")]
        public string Quantity { get; set; }

        [Required]
        [Display(Name = "Select the product type")]
        public string ProductType { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public string ExpireDate { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Provide the complain email address")]
        public string ComplainAddress { get; set; }
    }
}
