//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEF.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]

        [DataType(DataType.Password)]
        [MinLength(3)]
        
        public string Password { get; set; }



        [Display(Name = "Retype Password")]
        [Required]

        [DataType(DataType.Password)]
        [Compare("Password")]
        public string RePassword { get; set; }
        public string Type { get; set; }
    }

    public enum UserType
    {
        admin,
        member
    }
}
